# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: const.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='const.proto',
  package='',
  serialized_pb='\n\x0b\x63onst.proto*:\n\nScreenSize\x12\t\n\x05SMALL\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\t\n\x05LARGE\x10\x02\x12\n\n\x06XLARGE\x10\x03*Q\n\rScreenDensity\x12\x08\n\x04LDPI\x10\x00\x12\x08\n\x04MDPI\x10\x01\x12\x08\n\x04HDPI\x10\x02\x12\t\n\x05XHDPI\x10\x03\x12\n\n\x06XXHDPI\x10\x04\x12\x0b\n\x07XXXHDPI\x10\x05')

_SCREENSIZE = _descriptor.EnumDescriptor(
  name='ScreenSize',
  full_name='ScreenSize',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SMALL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LARGE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XLARGE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=15,
  serialized_end=73,
)

ScreenSize = enum_type_wrapper.EnumTypeWrapper(_SCREENSIZE)
_SCREENDENSITY = _descriptor.EnumDescriptor(
  name='ScreenDensity',
  full_name='ScreenDensity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LDPI', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MDPI', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HDPI', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XHDPI', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XXHDPI', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XXXHDPI', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=75,
  serialized_end=156,
)

ScreenDensity = enum_type_wrapper.EnumTypeWrapper(_SCREENDENSITY)
SMALL = 0
NORMAL = 1
LARGE = 2
XLARGE = 3
LDPI = 0
MDPI = 1
HDPI = 2
XHDPI = 3
XXHDPI = 4
XXXHDPI = 5




# @@protoc_insertion_point(module_scope)
